FROM node:16-alpine

USER node

WORKDIR /home/node/app

COPY --chown=node:node package.json .
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
RUN npm install
COPY --chown=node:node . .

CMD [ "npm", "start" ]