version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t stephengrider/docker-react -f Dockerfile.dev .
      - run:
          name: Run tests
          command: docker run -e CI=true stephengrider/docker-react npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
